app:
  title: HMCTS Backstage
  baseUrl: http://localhost:3000

organization:
  name: HMCTS

backend:
  baseUrl: http://localhost:7000
  listen:
    port: 7000
  # config options: https://node-postgres.com/api/client
  database:
    client: pg
    connection:
      host:
        $env: POSTGRES_HOST
      port:
        $env: POSTGRES_PORT
      user:
        $env: POSTGRES_USER
      password:
        $env: POSTGRES_PASSWORD
      ssl:
        $env: POSTGRES_SSL
  csp:
    connect-src: ["'self'", 'https:']
  cors:
    origin: http://localhost:3000
    methods: [GET, POST, PUT, DELETE]
    credentials: true

proxy:
  '/jenkins/api':
    target: 'http://jenkins.jenkins:8080'
    headers:
      Authorization:
        $env: JENKINS_BASIC_AUTH_HEADER

techdocs:
  storageUrl: http://localhost:7000/techdocs/static/docs
  requestUrl: http://localhost:7000/techdocs/docs
  generators:
    techdocs: 'local'

auth:
  providers:
    microsoft:
      development:
        clientId:
          $env: AUTH_MICROSOFT_CLIENT_ID
        clientSecret:
          $env: AUTH_MICROSOFT_CLIENT_SECRET
        tenantId:
          $env: AUTH_MICROSOFT_TENANT_ID


scaffolder:
  github:
    token:
      $env: GITHUB_ACCESS_TOKEN
    visibility: public # or 'internal' or 'private'
  integrations:
    github:
      - host: github.com
        token:
          $env: GITHUB_TOKEN

catalog:
  rules:
    - allow: [Component, API, Group, Template, Location]
  locations:
    # Backstage example components
    - type: github
      target: https://github.com/timja-org/rpe-sweet-backend/blob/master/api.yaml

    - type: github
      target: https://github.com/timja-org/rpe-sweet-backend/blob/master/component-info.yaml

    # HMCTS templates
    - type: github
      target: https://github.com/hmcts/template-expressjs/blob/master/template.yaml
      rules:
        - allow: [Template]
    - type: github
      target: https://github.com/hmcts/template-product-infrastructure/blob/master/template.yaml
      rules:
        - allow: [Template]
    - type: github
      target: https://github.com/hmcts/template-spring-boot/blob/master/template.yaml
      rules:
        - allow: [Template]
    - type: github
      target: https://github.com/hmcts/template-java-client/blob/master/template.yaml
      rules:
        - allow: [ Template ]
