app:
  title: HMCTS Backstage
  baseUrl: http://localhost:3000

organization:
  name: HMCTS

backend:
  baseUrl: http://localhost:7000
  listen:
    port: 7000
  cors:
    origin: http://localhost:3000
    methods: [GET, POST, PUT, DELETE]
    credentials: true
  database:
    client: pg
    connection:
      host:
        $secret:
          env: POSTGRES_HOST
      port:
        $secret:
          env: POSTGRES_PORT
      user:
        $secret:
          env: POSTGRES_USER
      password:
        $secret:
          env: POSTGRES_PASSWORD

proxy:
  '/jenkins/api':
    target: 'http://jenkins.jenkins:8080'
    headers:
      Authorization:
        $secret:
          env: JENKINS_BASIC_AUTH_HEADER

techdocs:
  storageUrl: http://localhost:7000/techdocs/static/docs

auth:
  providers:
    microsoft:
      development:
        clientId:
          $secret:
            env: AUTH_MICROSOFT_CLIENT_ID
        clientSecret:
          $secret:
            env: AUTH_MICROSOFT_CLIENT_SECRET
        tenantId:
          $secret:
            env: AUTH_MICROSOFT_TENANT_ID

# seems to be broken currently you need to manually add in UI
catalog:
  rules:
    - allow: [Component, API, Group, Template, Location]
  exampleEntityLocations:
    github:
      - https://github.com/hmcts/template-product-infrastructure/blob/master/template.yaml
      - https://github.com/hmcts/template-spring-boot/blob/master/template.yaml
      - https://github.com/hmcts/template-expressjs/blob/master/template.yaml
      - https://github.com/timja-org/rpe-sweet-backend/blob/master/api.yaml # example till we have better ones
      - https://github.com/timja-org/rpe-sweet-backend/blob/master/component-info.yaml # example till we have better ones
