app:
  title: HMCTS Backstage
  baseUrl: http://localhost:7000

organization:
  name: HMCTS

backend:
  baseUrl: http://localhost:7000
  listen:
    port: 7000
  # config options: https://node-postgres.com/api/client
  database:
    client: pg
    connection:
      host:
        $secret:
          env: POSTGRES_HOST
      port:
        $secret:
          env: POSTGRES_PORT
      user:
        $secret:
          env: POSTGRES_USER
      password:
        $secret:
          env: POSTGRES_PASSWORD
      ssl:
        $secret:
          env: POSTGRES_SSL

proxy:
  '/jenkins/api':
    target: 'http://jenkins.jenkins:8080'
    headers:
      Authorization:
        $secret:
          env: JENKINS_BASIC_AUTH_HEADER

techdocs:
  storageUrl: http://localhost:7000/techdocs/static/docs
  requestUrl: http://localhost:7000/techdocs/docs
  generators:
    techdocs: 'local'

auth:
  providers:
    microsoft:
      development:
        clientId:
          $secret:
            env: AUTH_MICROSOFT_CLIENT_ID
        clientSecret:
          $secret:
            env: AUTH_MICROSOFT_CLIENT_SECRET
        tenantId:
          $secret:
            env: AUTH_MICROSOFT_TENANT_ID


scaffolder:
  github:
    token:
      $secret:
        env: GITHUB_ACCESS_TOKEN
    visibility: public # or 'internal' or 'private'

catalog:
  rules:
    - allow: [Component, API, Group, Template, Location]
  processors:
    github:
      providers:
        - target: https://github.com
          token:
            $secret:
              env: GITHUB_PRIVATE_TOKEN
  locations:
    # Backstage example components
    - type: github
      target: https://github.com/timja-org/rpe-sweet-backend/blob/master/api.yaml

    - type: github
      target: https://github.com/timja-org/rpe-sweet-backend/blob/master/component-info.yaml

    # HMCTS templates
    - type: github
      target: https://github.com/hmcts/template-expressjs/blob/master/template.yaml
      rules:
        - allow: [Template]
    - type: github
      target: https://github.com/hmcts/template-product-infrastructure/blob/master/template.yaml
      rules:
        - allow: [Template]
    - type: github
      target: https://github.com/hmcts/template-spring-boot/blob/master/template.yaml
      rules:
        - allow: [Template]
    - type: github
      target: https://github.com/hmcts/template-java-client/blob/master/template.yaml
      rules:
        - allow: [ Template ]
