app:
  baseUrl: http://localhost:3000

backend:
  baseUrl: http://localhost:7000
  listen:
    port: 7000
  cors:
    origin: http://localhost:3000
    methods: [GET, POST, PUT, DELETE]
    credentials: true
proxy:
  '/jenkins/api':
    target: 'http://jenkins.jenkins:8080'
techdocs:
  storageUrl: http://localhost:7000/api/techdocs/static/docs
  requestUrl: http://localhost:7000/api/techdocs
  generators:
    techdocs: 'docker'