version: "3.8"
services:

  # backend:
  #   image: backstage
  #   environment:
  #     ROLLBAR_ACCOUNT_TOKEN: 'x'
  #     SENTRY_TOKEN: 'x'
  #     AUTH_GITHUB_CLIENT_ID: ${AUTH_GITHUB_CLIENT_ID}
  #     AUTH_GITHUB_CLIENT_SECRET: ${AUTH_GITHUB_CLIENT_SECRET}
  #     GITHUB_TOKEN: ${GITHUB_TOKEN}
  #     POSTGRES_HOST: db
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_USER: postgres
  #     AUTH_MICROSOFT_TENANT_ID: ${AUTH_MICROSOFT_TENANT_ID}
  #     AUTH_MICROSOFT_CLIENT_ID: ${AUTH_MICROSOFT_CLIENT_ID}
  #     AUTH_MICROSOFT_CLIENT_SECRET: ${AUTH_MICROSOFT_CLIENT_SECRET}
  #   ports:
  #     - "7007:7007"

  db:
    image: postgres:14
    #command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      #- ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      #- ./ca/server.crt:/var/lib/postgresql/server.crt
      #- ./ca/server.key:/var/lib/postgresql/server.key

volumes:
  db-data:
