apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: createDNSRecord
  title: Create a Public DNS Record 
  description: PR to create a public DNS record
  tags:
    - infrastructure
    - terraform
    - azure
    - dns
  annotations:
    backstage.io/techdocs-ref: https://backstage.io/docs/features/software-templates
  links:
    - title: Documentation
      url: https://backstage.io/docs/features/software-templates
      icon: docs
    - title: Source
      url: https://github.com.br/gabriel-dantas98/backstage-scaffolders/blob/main/basic-react-app/create-web-app.yaml
      icon: github

spec:
  owner: cloud_platform
  type: infra-as-code

  # parameters:
  # - title: Create a DNS record
  #   required:
  #       - dns_zone
  #       - record_name
  #       - record_value
  #       - record_ttl
  #   properties:
  #     dns_zone:
  #       title: DNS Zone name
  #       type: string
  #       enum:
  #         - platforms.hmcts.net
  #         - hmcts.net
  #       ui:autofocus: true
  #     record_name:
  #       title: DNS record name
  #       type: string
  #       description: |
  #         The name of the record to create
  #     record_value:
  #       title: DNS record value
  #       type: string
  #       description: |
  #         The value of the record to create
  #     record_ttl:
  #       title: DNS record time to live
  #       type: number
  #       description: |
  #         The TTL of the record
  # - title: Which environments to deploy the record to?
  #   required:
  #     - environments
  #   properties:
  #     environments:
  #       title: Select environments
  #       type: array
  #       items:
  #         type: string
  #         enum:
  #           - sbox 
  #           - dev 
  #           - ithc
  #           - demo
  #           - staging
  #           - prod
  #       uniqueItems: true
  #       ui:widget: checkboxes
  # - title: Which platform is this for?
  #   required:
  #     - cft_sds
  #   properties:
  #     cft_sds:
  #       title: Which platform does this DNS belong to? 
  #       type: string
  #       description: The DNS record should be assigned to a platform
  #       enum:
  #         - cft
  #         - sds
  #       ui:widget: radio
  parameters:
    - title: Create a DNS record
      required:
          - dns_zone
          - record_name
          - record_ttl
          - recordType
      properties:
        dns_zone:
          title: DNS Zone name
          type: string
          enum:
            - prod.internal.hmcts.net
            - platforms.hmcts.net
            - hmcts.net
          ui:autofocus: true
        record_name:
          title: DNS record name
          type: string
          description: |
            The name of the record to create
        record_ttl:
          title: DNS record time to live
          type: string
          description: |
            The TTL of the record
        recordType:
          type: string
          enum:
            - A
            - CNAME

      # Creating a dependency based on the selected technology above
      dependencies:
        recordType:
          oneOf:
            - properties:
                recordType:
                  enum:
                    - CNAME
                CNAME record Value:
                  type: "string"
                  description: A Record value to use with this CNAME entry
              required: 
                - CNAME record Value
            - properties:
                recordType:
                  enum:
                    - A
                A record value options:
                  type: "string"
                  description: Choose the values you want to provide for your DNS record
                  enum:
                    - Record value and Shutter Resource Id
                    - Record value and Alias Target Resource Id
                    - Alias Target Resource Id and Shutter Resource Id
                    - Record value, Alias Target Resource Id and Shutter Resource Id
              required: 
                - A record value options
              # Creating a dependency based on the selected java version (not necessary, just for example)
              dependencies:
                A record value options:
                  oneOf:
                    - properties: 
                        A record value options: 
                          enum:
                            - Record value and Shutter Resource Id
                        record_Value:
                          title: The value to use for this A record
                          type: string
                        shutter_resource_id:
                          title: The resource Id for the shutter page
                          type: string
                      required: 
                        - record_Value
                        - shutter_resource_id
                    - properties: 
                        A record value options: 
                          enum:
                            - Record value and Alias Target Resource Id
                        record_Value:
                          title: The value to use for this A record
                          type: string
                        alias_target_resource_id:
                          title: The resource Id for the alias target e.g. Frontdoor
                          type: string
                      required: 
                        - record_Value
                        - alias_target_resource_id
                    - properties: 
                        A record value options: 
                          enum:
                            - Alias Target Resource Id and Shutter Resource Id
                        alias_target_resource_id:
                          title: The resource Id for the alias target e.g. Frontdoor
                          type: string
                        shutter_resource_id:
                          title: The resource Id for the shutter page
                          type: string
                      required: 
                        - alias_target_resource_id
                        - shutter_resource_id
                    - properties: 
                        A record value options: 
                          enum:
                            - Record value, Alias Target Resource Id and Shutter Resource Id
                        record_Value:
                          title: The value to use for this A record
                          type: string
                        alias_target_resource_id:
                          title: The resource Id for the alias target e.g. Frontdoor
                          type: string
                        shutter_resource_id:
                          title: The resource Id for the shutter page
                          type: string
                      required: 
                        - record_Value
                        - alias_target_resource_id
                        - shutter_resource_id

    - title: Which environments to deploy the record to?
      required:
        - environments
      properties:
        environments:
          title: Select environments
          type: array
          items:
            type: string
            enum:
              - sbox 
              - dev 
              - ithc
              - demo
              - staging
              - prod
          uniqueItems: true
          ui:widget: checkboxes
    - title: Which platform is this for?
      required:
        - cft_sds
      properties:
        cft_sds:
          title: Which platform does this DNS belong to? 
          type: string
          description: The DNS record should be assigned to a platform
          enum:
            - cft
            - sds
          ui:widget: radio

  steps:

    - id: log-message
      name: Log Message
      action: debug:log
      input:
        message: Template execution started

    - id: trigger-ga
      name: Trigger GA workflow
      action: github:actions:dispatch
      input:
        repoUrl: github.com?repo=labs-mfox-nodejs&owner=hmcts
        branchOrTagName: master
        workflowId: backstage.yaml
        workflowInputs:
          dns_zone: ${{ parameters.dns_zone }}
          record_name: ${{ parameters.record_name }}
          record_value: ${{ parameters.record_value }}
          record_ttl: ${{ parameters.record_ttl }}
          record_type: ${{ parameters.recordType }}
          shutter_resource_id: ${{ parameters.shutter_resource_id }}
          alias_target_id: ${{ parameters.Alias_Target_Resource_Id }}
          # environments: ${{ parameters.environments }}
          cft_sds: ${{ parameters.cft_sds }}
        # token:
  
  output:
    links:
      - title: Public DNS Repo
        url: https://github.com/hmcts/labs-mfox-nodejs